obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.175, 0.175], [0.175, -0.175], [-0.175, -0.175], [-0.175, 0.175]]
footprint: [[0.25, 0.15], [0.25, -0.15], [-0.25, -0.15], [-0.25, 0.15]]
#footprint_inflation: 0.01
#robot_radius: 0.175
inflation_radius: 0.2
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: obstacle_clearing_filtered_scan, marking: true, clearing: true, expected_update_rate: 5, inf_is_valid: false}
